---
# tasks file for sphinx
- name: Run specified tasks on current platform
  include: "{{ ansible_os_family }}.yml"
- name: Install Sphinx
  pip:
    name: Sphinx
    version: "{{ sphinx_version | default(None) }}"
  become: yes
- name: Install Sphinx-related libraries
  pip:
    name: "{{ item }}"
  with_items:
    - sphinx-intl
  become: yes
